name: bb1girl CI/CD test
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      
  deploy:
    needs: ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Prepare SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/ci-sample-server.pem
          chmod 600 ~/.ssh/ci-sample-server.pem
          ssh-keyscan -H "${{ secrets.EC2_PUBLIC_IP }}" >> ~/.ssh/known_hosts

      - name: Copy project files to EC2
        run: |
          scp -i ~/.ssh/ci-sample-server.pem -r \
            dist \
            package.json \
            package-lock.json \
            tsconfig.json \
            tsconfig.build.json \
            ec2-user@${{ secrets.EC2_PUBLIC_IP }}:~/sample-server/

      - name: Restart app on EC2 with PM2
        run: |
          ssh -i ~/.ssh/ci-sample-server.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} '
            cd ~/sample-server && \
            npm ci && \
            pm2 restart sample-ci-server || pm2 start npm --name sample-server -- run start:prod
          '
